### ISSUE TITLE
Autoplay when open VSCode

### ISSUE THREAD

**Issue by general03** [AlexBlade/vscode-time-tracker#1]
Thanks a lot for this useful extension 

I would like to know if you plan to add configuration for enable the auto play timer when the project is open in VSCode.

It's the only feature that it miss in your extension according to me

Thanks again

**Comment by AlexBlade** [comment]
Thanks for you attention to the extension. Yes, I'm going to add some settings that will control timer's auto start when a project is opened. I guess this feature will appear during next week.

**Comment by AlexBlade** [comment]
Two options were added to control extension's behavior at the moment of project/folder opening.

- **timetracker.autostart.autoStartTimeTracking** - Automatically start time tracking when the project (folder) is opened and .timetracking file already exists in the project's folder
- **timetracker.autostart.autoCreateTimeTrackingFile** - Automatically start time tracking and create .timetracking file if it does not exist yet
