### ISSUE TITLE
No given way to turn off autopause feature.

### ISSUE THREAD

**Issue by ZackPlauche** [AlexBlade/vscode-time-tracker#6]
I really like this app overall, but the autopause feature keeps getting in the way.

I set the `"timetracker.delayBeforePause"` setting to `0` and it still stops after 2 minutes 🤷‍♂️. 

This feels like a bug, but maybe you can just add a boolean setting of something like `"timetracker.autoPause": false`

Or just some instructions on how to turn off the autopause feature, as setting it to zero does nothing right now.

**Comment by AlexBlade** [comment]
Thanks for info. I will check it as soon as possible,

**Comment by ipcjs** [comment]
Before the author fixes this problem, you can set "timetracker.delayBeforePause" to `999999999` :)

**Comment by ZackPlauche** [comment]
I tried that as well and it still stops at 2 minutes when you're not
focused on the window.

**Comment by AlexBlade** [comment]
There was a great and stupid bug. It was fixed, current version is 1.1.2. Please, take into attention that the parameter name was changed from "delayBeforePause" to "pauseAfter", you can find all parameters in the extension's description.
I will not close this issue for a while and would like to ask you to check if the parameter works according to your expectations.

**Comment by ZackPlauche** [comment]
Fixed! 🙂 I tested it by setting pauseAfter to zero (like in the instructions), clicking on a different window (on Windows 10) and going idle for a short time. It's been going for 20 min & hasn't stopped 🙂.

**Comment by AlexBlade** [comment]
Thanks a lot for your help, appreciate that! :)
This issue will be closed, if you will find any bugs or will have suggestions - you're welcome!
